# Homework 3  - Tryout pandas and numpy

https://github.com/SravanthiVillanova/big-data-python-class/tree/dev/Homeworks/Homework3 

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [5]:
import pandas as pd
current_data = pd.read_csv("data/ccp_current_csv.csv")    #reads data to current_data
current_data.head()                #prints first five rows of data

STREET QUADRANT  FROMINTERSECTION              TOINTERSECTION  \
0           13th St       NW        Kennedy St               Longfellow St   
1              S St       NW  North Capitol St                      3rd St   
2  Rhode Island Ave       NE  Brentwood Rd (W)            Brentwood Rd (M)   
3           Mill Rd       NW           27th St                  Cul De Sac   
4  Rhode Island Ave       NE  Brentwood Rd (M)  14th St  Evarts St  Montan   

   NOOFBLOCKS                 WORKDESCRIPTION  YEARBUDGETED  PERCENTCOMPLETED  \
0           1  Pavement Resurface/restoration          2004               100   
1           3                   Regular Cover          1999               100   
2           1  Pavement Resurface/restoration          2004               100   
3           1  Pavement Resurface/restoration          2004               100   
4           2  Pavement Resurface/restoration          2005               100   

      STATUS  MILES      ...             YCOORD   LATITUDE  LONGITUDE  \
0  Completed   0.07      ...       143205.11981  38.956747 -77.029694   
1  Completed   0.33      ...       138468.90256  38.914085 -77.012411   
2  Completed   0.09      ...       139574.10659  38.924041 -76.987221   
3  Completed   0.07      ...       138132.90198  38.911046 -77.054077   
4  Completed   0.16      ...       139657.25318  38.924790 -76.985068   

           PROJECTNOTE                                        PROJECTNAME  \
0                  NaN                                             FedAid   
1                  NaN                                                NaN   
2                  NaN           Fedral Aid Citywide Pavement Restoration   
3  POKA-2003-B-0048-JJ  Citywide Pavement Restoration Contract (Local ...   
4                  NaN                                                NaN   

          PROJECTMGR  PROJECTID        TEAMREP                 EMAIL  \
0    Paul Stephenson       5834        O. Hill                   NaN   
1                NaN       2467            NaN                   NaN   
2  Mohamed Abdullahi       5486   Said Cherifi   said.cherifi@dc.gov   
3    Maduabuchi Udeh       5796  Michael Jelen  Michael.Jelen@dc.gov   
4                NaN       8237            NaN                   NaN   

   CONTACTPHONE  
0  202-671-4591  
1           NaN  
2  202-671-4611  
3  202-671-4542  
4           NaN  

[5 rows x 27 columns]

### 3.1.a  what is its shape and what does that mean?

In [6]:
current_data.shape

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [12]:
print(current_data.QUADRANT.count())      #count of all the rows in a column
print(current_data.QUADRANT.value_counts())   #count of each type of value in a column

465
NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64


## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )

### 3.3.1 addition a+b 

In [14]:
import numpy as np
a = np.array([1,2,3,4], dtype=float)
b = np.array([5,6,7,8], dtype=float)

np.add(a,b)

array([  6.,   8.,  10.,  12.])

### 3.3.2 subtraction a-b

In [15]:
np.subtract(a,b)

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [16]:
np.multiply(a,b)

array([  5.,  12.,  21.,  32.])

### 3.3.4 divsion a/b

In [17]:
np.divide(a,b)

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

### 3.3.5 modulo  a%b

In [18]:
np.mod(a,b)

array([ 1.,  2.,  3.,  4.])

### 3.3.6 power  a^b

In [19]:
np.power(a,b)

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

## Homework 3.4
Find your own data and load it into a dataframe

#### Gapminder Dataset
I refered 'Pandas for Everyone' by Daniel Y.Chen for this assignment. I took a dataset from gapminder suggested in the book. It refered to the url https://github.com/jennybc/gapminder <br>
This data set has six variables, life expectancy, population, percapita gdp of every country(its continent) for years from 1952 to 2007.

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', 15)   #Configuring output display to restrict number of rows dsplayed to 15 and width to 100
pd.set_option('display.width', 100)

dev_stats = pd.read_csv('data/gapminder.tsv', sep='\t')      #read data from .tsv file
print(dev_stats.head())              #displays first 5 observations from dataset

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [3]:
dev_stats.columns     # List of variable names in the dataset

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [4]:
dev_stats.describe()  #Summary of all variables

year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165877
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846989
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [5]:
dev_stats.shape       #Gives observations,variables in dataset. There are 1704 observations with 6 variables

(1704, 6)

In [6]:
dev_stats.dtypes     #Gives data types of variables in dev_stats

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [7]:
dev_stats.info()    #Summary of entire dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
country      1704 non-null object
continent    1704 non-null object
year         1704 non-null int64
lifeExp      1704 non-null float64
pop          1704 non-null int64
gdpPercap    1704 non-null float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [8]:
dev_names = dev_stats[['continent','country','year']]  #Subsetting columns, create a dataframe from a list of columns 
dev_names.head()

continent      country  year
0      Asia  Afghanistan  1952
1      Asia  Afghanistan  1957
2      Asia  Afghanistan  1962
3      Asia  Afghanistan  1967
4      Asia  Afghanistan  1972

#### Average (mean) life expectancy for the entire data

In [9]:
dev_stats['lifeExp'].mean()     #average life expectancy of all the observations

59.47443936619713

#### Get the data for continent Asia

In [10]:
dev_stats.loc[dev_stats['continent'] == 'Asia']    #Retrieve observations matching a column condition

country continent  year  lifeExp       pop    gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333   779.445314
1     Afghanistan      Asia  1957   30.332   9240934   820.853030
2     Afghanistan      Asia  1962   31.997  10267083   853.100710
3     Afghanistan      Asia  1967   34.020  11537966   836.197138
4     Afghanistan      Asia  1972   36.088  13079460   739.981106
5     Afghanistan      Asia  1977   38.438  14880372   786.113360
6     Afghanistan      Asia  1982   39.854  12881816   978.011439
...           ...       ...   ...      ...       ...          ...
1673  Yemen, Rep.      Asia  1977   44.175   8403990  1829.765177
1674  Yemen, Rep.      Asia  1982   49.113   9657618  1977.557010
1675  Yemen, Rep.      Asia  1987   52.922  11219340  1971.741538
1676  Yemen, Rep.      Asia  1992   55.599  13367997  1879.496673
1677  Yemen, Rep.      Asia  1997   58.020  15826497  2117.484526
1678  Yemen, Rep.      Asia  2002   60.308  18701257  2234.820827
1679  Yemen, Rep.      Asia  2007   62.698  22211743  2280.769906

[396 rows x 6 columns]

#### Average life expectancy for each year? 

In [86]:
#group by year
grp_by_yr = dev_stats.groupby('year')   #Groups data in varables year and continent
grp_by_yr
#grp_by_yr.groups               #gives groups in grp_by_yr
grp_by_yr['lifeExp'].mean()     #gives average life expectancy for each year

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

#### Average life expectancy for each continent for every year.

In [91]:
grp_by_cnt_yr = dev_stats.groupby(['year','continent'])    #Groups data in varables year and continent
grp_by_cnt_yr.head()

country continent  year  lifeExp       pop     gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333    779.445314
1     Afghanistan      Asia  1957   30.332   9240934    820.853030
2     Afghanistan      Asia  1962   31.997  10267083    853.100710
3     Afghanistan      Asia  1967   34.020  11537966    836.197138
4     Afghanistan      Asia  1972   36.088  13079460    739.981106
5     Afghanistan      Asia  1977   38.438  14880372    786.113360
6     Afghanistan      Asia  1982   39.854  12881816    978.011439
...           ...       ...   ...      ...       ...           ...
1097  New Zealand   Oceania  1977   72.220   3164900  16233.717700
1098  New Zealand   Oceania  1982   73.840   3210650  17632.410400
1099  New Zealand   Oceania  1987   74.320   3317166  19007.191290
1100  New Zealand   Oceania  1992   76.330   3437674  18363.324940
1101  New Zealand   Oceania  1997   77.550   3676187  21050.413770
1102  New Zealand   Oceania  2002   79.110   3908037  23189.801350
1103  New Zealand   Oceania  2007   80.204   4115771  25185.009110

[264 rows x 6 columns]

In [92]:
grp_by_cnt_yr['lifeExp'].mean()     #avg life expectancy for every continent for each year

year  continent
1952  Africa       39.135500
      Americas     53.279840
      Asia         46.314394
      Europe       64.408500
      Oceania      69.255000
1957  Africa       41.266346
      Americas     55.960280
                     ...    
2002  Europe       76.700600
      Oceania      79.740000
2007  Africa       54.806038
      Americas     73.608120
      Asia         70.728485
      Europe       77.648600
      Oceania      80.719500
Name: lifeExp, Length: 60, dtype: float64

#### Average life expectancy, population, Percapita gdp of every continent for each year

In [93]:
grp_by_cnt_yr[['lifeExp','pop','gdpPercap']].mean() #Average of life expectancy,population, gdp country wise for every year.

lifeExp           pop     gdpPercap
year continent                                       
1952 Africa     39.135500  4.570010e+06   1252.572466
     Americas   53.279840  1.380610e+07   4079.062552
     Asia       46.314394  4.228356e+07   5195.484004
     Europe     64.408500  1.393736e+07   5661.057435
     Oceania    69.255000  5.343003e+06  10298.085650
1957 Africa     41.266346  5.093033e+06   1385.236062
     Americas   55.960280  1.547816e+07   4616.043733
...                   ...           ...           ...
2002 Europe     76.700600  1.927413e+07  21711.732422
     Oceania    79.740000  1.172741e+07  26938.778040
2007 Africa     54.806038  1.787576e+07   3089.032605
     Americas   73.608120  3.595485e+07  11003.031625
     Asia       70.728485  1.155138e+08  12473.026870
     Europe     77.648600  1.953662e+07  25054.481636
     Oceania    80.719500  1.227497e+07  29810.188275

[60 rows x 3 columns]

#### Sort data based on gdpPercap in descending order for a particular year

In [11]:
grp_yr = dev_stats.groupby(['year']).filter(lambda x: (x['year'] == 2007).any())
grp_yr.sort_values('gdpPercap', ascending = False)

country continent  year  lifeExp        pop     gdpPercap
1151            Norway    Europe  2007   80.196    4627926  49357.190170
863             Kuwait      Asia  2007   77.588    2505559  47306.989780
1367         Singapore      Asia  2007   79.972    4553009  47143.179640
1619     United States  Americas  2007   78.242  301139947  42951.653090
755            Ireland    Europe  2007   78.885    4109086  40675.996350
671   Hong Kong, China      Asia  2007   82.208    6980412  39724.978670
1487       Switzerland    Europe  2007   81.701    7554661  37506.419070
...                ...       ...   ...      ...        ...           ...
503            Eritrea    Africa  2007   58.040    4906585    641.369524
1127             Niger    Africa  2007   56.867   12894865    619.676892
635      Guinea-Bissau    Africa  2007   46.388    1472041    579.231743
1703          Zimbabwe    Africa  2007   43.487   12311143    469.709298
215            Burundi    Africa  2007   49.580    8390505    430.070692
899            Liberia    Africa  2007   45.678    3193942    414.507341
335   Congo, Dem. Rep.    Africa  2007   46.462   64606759    277.551859

[142 rows x 6 columns]

To sort gdpPercap data in descending order for year 2007: <br>
1. Grouped observations year wise and filtered the rows using flter(), lambda to select 2007 year observations.
2. Sorted the resulting observations using sort_values by 'gdpPercap'.

#### Frequency distribution of columns

In [12]:
grp_by_cnt_cntry = dev_stats.groupby(['continent','country'])
grp_by_cnt_cntry.head(5)
print('\033[1m' + '\nFrequency Distribution for continent column\n' + '\033[0m')
print(grp_by_cnt_cntry['continent'].value_counts())       #Gives each value frequency for continent
print('\033[1m' + '\nFrequency Distribution for life expectancy column\n' + '\033[0m')
print(grp_by_cnt_cntry['lifeExp'].value_counts())
print('\033[1m' + '\nFrequency Distribution for population column\n' + '\033[0m')
print(grp_by_cnt_cntry['pop'].value_counts())
print('\033[1m' + '\nFrequency Distribution for gdp Percapita column\n' + '\033[0m')
print(grp_by_cnt_cntry['gdpPercap'].value_counts())


Frequency Distribution for continent column

continent  country         continent
Africa     Algeria         Africa       12
           Angola          Africa       12
           Benin           Africa       12
           Botswana        Africa       12
           Burkina Faso    Africa       12
           Burundi         Africa       12
           Cameroon        Africa       12
                                        ..
Europe     Spain           Europe       12
           Sweden          Europe       12
           Switzerland     Europe       12
           Turkey          Europe       12
           United Kingdom  Europe       12
Oceania    Australia       Oceania      12
           New Zealand     Oceania      12
Name: continent, Length: 142, dtype: int64

Frequency Distribution for life expectancy column

continent  country      lifeExp
Africa     Algeria      43.077     1
                        45.685     1
                        48.303     1
                        51.407    

### HR Data
I refered Kaggle for this dataset. https://www.kaggle.com/ludobenistant/hr-analytics
This is a hr dataset used to analyse the attrition rate of company. It has employee data.

In [13]:
%matplotlib inline

# import numpy and pandas
import numpy as np
import pandas as pd

# Set format options
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 130)

# load the HR data
hr_data = pd.read_csv("data/HR_comma_sep.csv")
hr_data.head()  

   satisfaction_level  last_evaluation  number_project  average_montly_hours  time_spend_company  Work_accident  left  \
0                0.38             0.53               2                   157                   3              0     1   
1                0.80             0.86               5                   262                   6              0     1   
2                0.11             0.88               7                   272                   4              0     1   
3                0.72             0.87               5                   223                   5              0     1   
4                0.37             0.52               2                   159                   3              0     1   

   promotion_last_5years  sales  salary  
0                      0  sales     low  
1                      0  sales  medium  
2                      0  sales  medium  
3                      0  sales     low  
4                      0  sales     low  

In [14]:
hr_data.shape    #Gives observations,variables in dataset. There are 14999 observations with 10 variables

(14999, 10)

In [15]:
hr_data.columns    # List of variable names in the dataset

Index(['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company', 'Work_accident',
       'left', 'promotion_last_5years', 'sales', 'salary'],
      dtype='object')

In [16]:
grouped_by_salary = hr_data.groupby('salary')
grouped_by_salary.ngroups    # Get the number of groups in 'salary'

3

In [17]:
grouped_by_salary.groups    # Groups in the variable 'salary'

{'high': Int64Index([   72,   111,   189,   267,   306,   345,   384,   423,   462,   501,
             ...
             14634, 14673, 14712, 14751, 14790, 14829, 14868, 14902, 14941, 14980],
            dtype='int64', length=1237),
 'low': Int64Index([    0,     3,     4,     5,     6,     7,     8,     9,    10,    11,
             ...
             14989, 14990, 14991, 14992, 14993, 14994, 14995, 14996, 14997, 14998],
            dtype='int64', length=7316),
 'medium': Int64Index([    1,     2,    60,    61,    62,    63,    64,    65,    66,    67,
             ...
             14974, 14975, 14976, 14977, 14978, 14979, 14982, 14983, 14984, 14985],
            dtype='int64', length=6446)}

In [18]:
grouped_by_salary.size()      # get how many observations are in each group

salary
high      1237
low       7316
medium    6446
dtype: int64

In [19]:
# get the descriptive statistics for each group
grouped_by_salary.describe()

       Work_accident                                ...  time_spend_company                     
               count      mean       std  min  25%  ...                 min  25%  50%  75%   max
salary                                              ...                                         
high          1237.0  0.155214  0.362255  0.0  0.0  ...                 2.0  3.0  3.0  4.0  10.0
low           7316.0  0.142154  0.349232  0.0  0.0  ...                 2.0  3.0  3.0  4.0  10.0
medium        6446.0  0.145361  0.352492  0.0  0.0  ...                 2.0  3.0  3.0  4.0  10.0

[3 rows x 64 columns]

There are 319 people who got promotion in the last 5 years and 14680 people who did not get promotion

In [20]:
promote = hr_data['promotion_last_5years'].value_counts()
promote                         

0    14680
1      319
Name: promotion_last_5years, dtype: int64

3571 people left the company

In [21]:
left = hr_data['left'].value_counts()[1]
left

3571

In [22]:
hr_data['satisfaction_level'].mean()   # Average satisfaction level of all the employees

0.6128335222348166

Mean satisfaction level of employees who left the organisation and did not. '0' indicates employees who did not leave. 0.666810 is the average satisfaction level of employees who did not leave and 0.440098 is the average satisfaction level of employees who left. This is a good indicator to predict who will leave the organization.

In [24]:
avg_satisfaction_by_left = hr_data.groupby('left')['satisfaction_level'].mean()
avg_satisfaction_by_left

left
0    0.666810
1    0.440098
Name: satisfaction_level, dtype: float64

In [25]:
hr_data['last_evaluation'].mean() # Average evaluation score of all the employees in the organisation in their 'last evaluation'

0.7161017401159978

It seems the last evaluation scores of both the groups are almost same, which indicates that this is not a good indicator to predict the people who will leave the organization

In [26]:
avg_evaluation_by_left = hr_data.groupby('left')['last_evaluation'].mean()
avg_evaluation_by_left

left
0    0.715473
1    0.718113
Name: last_evaluation, dtype: float64

In [27]:
hr_data['time_spend_company'].mean()   # Average time spent by all employees in the company

3.498233215547703

Average time spent in the organisation by employees who left the company is 3.876505 years

In [28]:
avg_time_by_left = hr_data.groupby('left')['time_spend_company'].mean()
avg_time_by_left

left
0    3.380032
1    3.876505
Name: time_spend_company, dtype: float64

In [29]:
hr_data.mean()['average_montly_hours']     # Average monthly hours worked by the employees

201.05033668911261

In [30]:
hr_data.mean()['average_montly_hours']/30  # Average hours worked by the employees in a day

6.7016778896370868

The average monthly hours based on salary level

In [32]:
month_hours_sal = hr_data[['average_montly_hours','salary']].groupby('salary').mean()
print(month_hours_sal)

        average_montly_hours
salary                      
high              199.867421
low               200.996583
medium            201.338349


The average satisfaction level of employees according to the salary level. It seems that the employees with 'low salary' group are less satisfied in their job

In [33]:
hr_data.groupby('salary').mean()['satisfaction_level']

salary
high      0.637470
low       0.600753
medium    0.621817
Name: satisfaction_level, dtype: float64

#### References
'Pandas for Everyone' by Daniel Y.Chen <br>.
I refered below urls also:
http://cfss.uchicago.edu/fall2016/hw05-python-data-analysis.html
https://rstudio-pubs-static.s3.amazonaws.com/224357_21e4c561d34f4f4887dae1ba77ada811.html
https://www.kaggle.com/ludobenistant/hr-analytics